/**
 * Receives screenshots from the share sheet in a tiny native activity and hands them to the running
 * app, instead of letting the share sheet start MainActivity itself.
 *
 * Why: when GPay / PhonePe / BHIM share into MainActivity, Android starts new MainActivity instances
 * even though it is singleTask (the diagnostics log showed two new copies per share). Each instance
 * mounts another React tree in the same JS runtime, and every tree's navigation container listens to
 * Expo Router's one global navigation queue: a hidden copy takes "open Scan" (Scan never opens) or a
 * copy that isn't ready runs it (the "Attempted to navigate before mounting the Root Layout" crash).
 *
 * ShareReceiverActivity has no React and no UI: it re-sends the share to MainActivity with
 * FLAG_ACTIVITY_NEW_TASK, which for a singleTask activity reaches the existing instance through
 * onNewIntent (or starts it once on a cold start), then finishes. expo-share-intent reads the share
 * from there as before.
 *
 * Moves the SEND / SEND_MULTIPLE filters that expo-share-intent puts on MainActivity, so it must be
 * listed before expo-share-intent in app.config.ts (manifest mods run last-listed first).
 * Generates at prebuild (never edit android/).
 */
const fs = require('fs');
const path = require('path');
const { AndroidConfig, withAndroidManifest, withDangerousMod } = require('expo/config-plugins');

const SHARE_ACTIONS = ['android.intent.action.SEND', 'android.intent.action.SEND_MULTIPLE'];

const activityKt = (pkg) => `// Generated by plugins/withShareReceiver.js
package ${pkg}

import android.app.Activity
import android.content.Intent
import android.os.Bundle

class ShareReceiverActivity : Activity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    // Same action, type, extras and ClipData (the shared files); fresh flags so nothing from the
    // sender (new document, multiple task, forward result) makes Android start another instance.
    val forward = Intent(intent)
      .setClass(this, MainActivity::class.java)
      .setFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_GRANT_READ_URI_PERMISSION)
    startActivity(forward)
    finish()
  }
}
`;

const isShareFilter = (f) => (f.action ?? []).some((a) => SHARE_ACTIONS.includes(a.$['android:name']));

const withShareReceiverFile = (config) =>
  withDangerousMod(config, [
    'android',
    (c) => {
      const pkg = c.android?.package;
      if (!pkg) throw new Error('withShareReceiver: app config needs `android.package`');
      const kt = path.join(c.modRequest.platformProjectRoot, 'app/src/main/java', ...pkg.split('.'), 'ShareReceiverActivity.kt');
      fs.mkdirSync(path.dirname(kt), { recursive: true });
      fs.writeFileSync(kt, activityKt(pkg));
      return c;
    },
  ]);

const withShareReceiverManifest = (config) =>
  withAndroidManifest(config, (c) => {
    const main = AndroidConfig.Manifest.getMainActivityOrThrow(c.modResults);
    const filters = (main['intent-filter'] ?? []).filter(isShareFilter);
    if (!filters.length) throw new Error('withShareReceiver: no share filters on MainActivity (list it before expo-share-intent)');
    main['intent-filter'] = main['intent-filter'].filter((f) => !isShareFilter(f));

    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(c.modResults);
    app.activity = (app.activity ?? []).filter((a) => a.$['android:name'] !== '.ShareReceiverActivity');
    app.activity.push({
      $: {
        'android:name': '.ShareReceiverActivity',
        'android:exported': 'true',
        'android:excludeFromRecents': 'true',
        'android:noHistory': 'true',
        'android:taskAffinity': '',
        'android:theme': '@android:style/Theme.Translucent.NoTitleBar',
      },
      'intent-filter': filters,
    });
    return c;
  });

module.exports = (config) => withShareReceiverManifest(withShareReceiverFile(config));
