/**
 * "Quick add" home-screen widget: app logo + Expense / Income / Scan buttons.
 *
 * Action-only on purpose: it shows no amounts, so nothing financial appears on the home screen
 * outside the app lock and screenshot protection. Each button is a deep link on the app's scheme
 * (the same mechanism as the launcher shortcuts), so Expo Router opens the screen and the app lock
 * still applies. It never needs data updates, so there is no background work.
 *
 * Generates at prebuild (never edit android/ by hand):
 * - QuickAddWidget.kt: AppWidgetProvider wiring the buttons to PendingIntents
 * - res/layout/widget_quick_add.xml, res/drawable/widget_*.xml backgrounds, glyph PNGs
 * - res/xml/widget_quick_add_info.xml provider info, <receiver> in the manifest, strings
 */
const fs = require('fs');
const path = require('path');
const { AndroidConfig, withAndroidManifest, withDangerousMod, withStringsXml } = require('expo/config-plugins');

const BUTTONS = [
  { id: 'widget_expense', label: 'Expense', icon: 'expense', path: 'txn/new?type=expense' },
  { id: 'widget_income', label: 'Income', icon: 'income', path: 'txn/new?type=income' },
  { id: 'widget_scan', label: 'Scan', icon: 'scan', path: 'scan' },
];
const BRAND = '#4F46E5';

const layoutXml = () => `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAndroidWidget.js -->
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
  android:id="@android:id/background"
  android:layout_width="match_parent"
  android:layout_height="match_parent"
  android:orientation="horizontal"
  android:gravity="center_vertical"
  android:padding="6dp"
  android:background="@drawable/widget_background">

  <ImageView
    android:id="@+id/widget_open"
    android:layout_width="44dp"
    android:layout_height="44dp"
    android:padding="4dp"
    android:layout_marginEnd="4dp"
    android:src="@drawable/widget_logo"
    android:scaleType="fitCenter"
    android:contentDescription="@string/widget_open" />
${BUTTONS.map(
  (b) => `
  <LinearLayout
    android:id="@+id/${b.id}"
    android:layout_width="0dp"
    android:layout_height="match_parent"
    android:layout_weight="1"
    android:layout_marginStart="4dp"
    android:orientation="vertical"
    android:gravity="center"
    android:minHeight="44dp"
    android:background="@drawable/widget_button"
    android:contentDescription="@string/${b.id}">
    <ImageView
      android:layout_width="22dp"
      android:layout_height="22dp"
      android:src="@drawable/widget_icon_${b.icon}"
      android:importantForAccessibility="no" />
    <TextView
      android:layout_width="wrap_content"
      android:layout_height="wrap_content"
      android:layout_marginTop="2dp"
      android:text="@string/${b.id}"
      android:textColor="#FFFFFF"
      android:textSize="12sp"
      android:textStyle="bold"
      android:maxLines="1" />
  </LinearLayout>`,
).join('\n')}
</LinearLayout>
`;

const backgroundXml = `<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle">
  <solid android:color="${BRAND}" />
  <corners android:radius="24dp" />
</shape>
`;

// Translucent white pill; pressed state is darker so a tap is visible.
const buttonXml = `<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
  <item android:state_pressed="true">
    <shape android:shape="rectangle"><solid android:color="#40FFFFFF" /><corners android:radius="16dp" /></shape>
  </item>
  <item>
    <shape android:shape="rectangle"><solid android:color="#22FFFFFF" /><corners android:radius="16dp" /></shape>
  </item>
</selector>
`;

const providerXml = `<?xml version="1.0" encoding="utf-8"?>
<appwidget-provider xmlns:android="http://schemas.android.com/apk/res/android"
  android:minWidth="250dp"
  android:minHeight="40dp"
  android:minResizeWidth="180dp"
  android:minResizeHeight="40dp"
  android:targetCellWidth="4"
  android:targetCellHeight="1"
  android:maxResizeHeight="110dp"
  android:resizeMode="horizontal|vertical"
  android:updatePeriodMillis="0"
  android:initialLayout="@layout/widget_quick_add"
  android:previewLayout="@layout/widget_quick_add"
  android:previewImage="@drawable/widget_preview"
  android:description="@string/widget_description"
  android:widgetCategory="home_screen" />
`;

const providerKt = (pkg, scheme) => `// Generated by plugins/withAndroidWidget.js. Do not edit: run \`npx expo prebuild\`.
package ${pkg}

import android.app.PendingIntent
import android.appwidget.AppWidgetManager
import android.appwidget.AppWidgetProvider
import android.content.Context
import android.content.Intent
import android.net.Uri
import android.widget.RemoteViews

/** Home-screen "quick add" bar. Buttons are deep links; the widget never shows amounts. */
class QuickAddWidget : AppWidgetProvider() {
  override fun onUpdate(context: Context, manager: AppWidgetManager, ids: IntArray) {
    val views = RemoteViews(context.packageName, R.layout.widget_quick_add)
    views.setOnClickPendingIntent(R.id.widget_open, open(context, "${scheme}://", 0))
${BUTTONS.map((b, i) => `    views.setOnClickPendingIntent(R.id.${b.id}, open(context, "${scheme}://${b.path}", ${i + 1}))`).join('\n')}
    for (id in ids) manager.updateAppWidget(id, views)
  }

  private fun open(context: Context, uri: String, requestCode: Int): PendingIntent {
    val intent = Intent(Intent.ACTION_VIEW, Uri.parse(uri))
      .setClass(context, MainActivity::class.java)
      .addFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TOP)
    return PendingIntent.getActivity(context, requestCode, intent, PendingIntent.FLAG_IMMUTABLE or PendingIntent.FLAG_UPDATE_CURRENT)
  }
}
`;

const withWidgetFiles = (config) =>
  withDangerousMod(config, [
    'android',
    (c) => {
      const root = c.modRequest.projectRoot;
      const main = path.join(c.modRequest.platformProjectRoot, 'app/src/main');
      const res = path.join(main, 'res');
      const scheme = Array.isArray(c.scheme) ? c.scheme[0] : c.scheme;
      const pkg = c.android?.package;
      if (!scheme || !pkg) throw new Error('withAndroidWidget: app config needs `scheme` and `android.package`');

      const write = (rel, text) => {
        const file = path.join(res, rel);
        fs.mkdirSync(path.dirname(file), { recursive: true });
        fs.writeFileSync(file, text);
      };
      const copy = (src, rel) => {
        const from = path.join(root, src);
        if (!fs.existsSync(from)) throw new Error(`withAndroidWidget: missing ${from} (run assets/source/render-glyphs.sh)`);
        fs.mkdirSync(path.join(res, path.dirname(rel)), { recursive: true });
        fs.copyFileSync(from, path.join(res, rel));
      };

      write('layout/widget_quick_add.xml', layoutXml());
      write('drawable/widget_background.xml', backgroundXml);
      write('drawable/widget_button.xml', buttonXml);
      write('xml/widget_quick_add_info.xml', providerXml);
      copy('assets/splash-icon.png', 'drawable-nodpi/widget_logo.png');
      copy('assets/widget/preview.png', 'drawable-nodpi/widget_preview.png');
      for (const b of BUTTONS) copy(`assets/widget/${b.icon}.png`, `drawable-nodpi/widget_icon_${b.icon}.png`);

      const kt = path.join(main, 'java', ...pkg.split('.'), 'QuickAddWidget.kt');
      fs.mkdirSync(path.dirname(kt), { recursive: true });
      fs.writeFileSync(kt, providerKt(pkg, scheme));
      return c;
    },
  ]);

const withWidgetStrings = (config) =>
  withStringsXml(config, (c) => {
    c.modResults = AndroidConfig.Strings.setStringItem(
      [
        { $: { name: 'widget_label' }, _: 'Quick add' },
        { $: { name: 'widget_description' }, _: 'Add an expense, income or screenshot in one tap. Shows no amounts.' },
        { $: { name: 'widget_open' }, _: 'Open ExpenseMonster' },
        ...BUTTONS.map((b) => ({ $: { name: b.id }, _: b.label })),
      ],
      c.modResults,
    );
    return c;
  });

const withWidgetReceiver = (config) =>
  withAndroidManifest(config, (c) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(c.modResults);
    const receivers = (app.receiver ?? []).filter((r) => r.$['android:name'] !== '.QuickAddWidget');
    receivers.push({
      $: { 'android:name': '.QuickAddWidget', 'android:exported': 'false', 'android:label': '@string/widget_label' },
      'intent-filter': [{ action: [{ $: { 'android:name': 'android.appwidget.action.APPWIDGET_UPDATE' } }] }],
      'meta-data': [{ $: { 'android:name': 'android.appwidget.provider', 'android:resource': '@xml/widget_quick_add_info' } }],
    });
    app.receiver = receivers;
    return c;
  });

module.exports = (config) => withWidgetReceiver(withWidgetStrings(withWidgetFiles(config)));
