/**
 * Static Android launcher shortcuts: long-press the app icon (or drag one onto the home screen).
 *
 * Each shortcut is a deep link on the app's own scheme, so Expo Router opens the screen with no
 * extra JS. Static shortcuts appear right after install. The app lock still covers whatever opens,
 * and before onboarding the root layout redirects to /onboarding as usual.
 *
 * Generates (Continuous Native Generation; never edit android/ by hand):
 * - res/xml/shortcuts.xml + <meta-data android.app.shortcuts> on MainActivity
 * - res/drawable-anydpi-v26/shortcut_<icon>.xml adaptive icons (white background, foreground PNG
 *   from assets/shortcuts, rendered by assets/source/render-shortcuts.sh)
 * - string resources for the labels (Android requires @string references here)
 */
const fs = require('fs');
const path = require('path');
const { AndroidConfig, withAndroidManifest, withDangerousMod, withStringsXml } = require('expo/config-plugins');

/** Max 4 is what launchers reliably show. Short label ≤ 10 chars, long label ≤ 25. */
const SHORTCUTS = [
  { id: 'add_expense', short: 'Expense', long: 'Add an expense', icon: 'expense', path: 'txn/new?type=expense' },
  { id: 'scan', short: 'Scan', long: 'Scan a payment screenshot', icon: 'scan', path: 'scan' },
  { id: 'dues', short: 'Dues', long: 'See what is due', icon: 'dues', path: 'dues' },
  { id: 'assistant', short: 'Ask', long: 'Ask the assistant', icon: 'assistant', path: 'assistant' },
];

const xmlEscape = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

function shortcutsXml(scheme, pkg) {
  const items = SHORTCUTS.map(
    (s) => `  <shortcut
    android:shortcutId="${s.id}"
    android:enabled="true"
    android:icon="@drawable/shortcut_${s.icon}"
    android:shortcutShortLabel="@string/shortcut_${s.id}_short"
    android:shortcutLongLabel="@string/shortcut_${s.id}_long">
    <intent
      android:action="android.intent.action.VIEW"
      android:targetPackage="${pkg}"
      android:targetClass="${pkg}.MainActivity"
      android:data="${xmlEscape(`${scheme}://${s.path}`)}" />
  </shortcut>`,
  ).join('\n');
  return `<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by plugins/withAndroidShortcuts.js -->\n<shortcuts xmlns:android="http://schemas.android.com/apk/res/android">\n${items}\n</shortcuts>\n`;
}

const adaptiveXml = (icon) => `<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
  <background android:drawable="@android:color/white" />
  <foreground android:drawable="@drawable/shortcut_${icon}_fg" />
</adaptive-icon>
`;

const withShortcutFiles = (config) =>
  withDangerousMod(config, [
    'android',
    (c) => {
      const res = path.join(c.modRequest.platformProjectRoot, 'app/src/main/res');
      const scheme = Array.isArray(c.scheme) ? c.scheme[0] : c.scheme;
      const pkg = c.android?.package;
      if (!scheme || !pkg) throw new Error('withAndroidShortcuts: app config needs `scheme` and `android.package`');

      const dirs = ['xml', 'drawable-nodpi', 'drawable-anydpi-v26'].map((d) => path.join(res, d));
      for (const d of dirs) fs.mkdirSync(d, { recursive: true });
      const [xmlDir, nodpi, anydpi] = dirs;

      fs.writeFileSync(path.join(xmlDir, 'shortcuts.xml'), shortcutsXml(scheme, pkg));
      for (const icon of new Set(SHORTCUTS.map((s) => s.icon))) {
        const src = path.join(c.modRequest.projectRoot, 'assets/shortcuts', `${icon}.png`);
        if (!fs.existsSync(src)) throw new Error(`withAndroidShortcuts: missing ${src} (run assets/source/render-shortcuts.sh)`);
        fs.copyFileSync(src, path.join(nodpi, `shortcut_${icon}_fg.png`));
        fs.writeFileSync(path.join(anydpi, `shortcut_${icon}.xml`), adaptiveXml(icon));
      }
      return c;
    },
  ]);

const withShortcutStrings = (config) =>
  withStringsXml(config, (c) => {
    const items = SHORTCUTS.flatMap((s) => [
      { $: { name: `shortcut_${s.id}_short` }, _: s.short },
      { $: { name: `shortcut_${s.id}_long` }, _: s.long },
    ]);
    c.modResults = AndroidConfig.Strings.setStringItem(items, c.modResults);
    return c;
  });

const withShortcutsMetaData = (config) =>
  withAndroidManifest(config, (c) => {
    const activity = AndroidConfig.Manifest.getMainActivityOrThrow(c.modResults);
    const others = (activity['meta-data'] ?? []).filter((m) => m.$['android:name'] !== 'android.app.shortcuts');
    activity['meta-data'] = [...others, { $: { 'android:name': 'android.app.shortcuts', 'android:resource': '@xml/shortcuts' } }];
    return c;
  });

module.exports = (config) => withShortcutsMetaData(withShortcutStrings(withShortcutFiles(config)));
module.exports.SHORTCUTS = SHORTCUTS;
